"""The worker profile: which routes an AI-Worker process serves, and only those.

v11.6.0 turns ``lattice-host`` into the product server (plan §설계 결정 1): 439
of the 464 Python routes become native axum handlers, and the proxy fall-through
is inverted into an allowlist that passes **only** the worker's own surface. The
allowlist and this module's :data:`WORKER_ROUTES` are the same contract read from
opposite ends, so it is written down once, here, as data.

Two honest boundaries, because a reader will otherwise assume more:

* **This profile shrinks the HTTP surface, not the construction.** WP-P1
  deleted the keep-set's complement, so the six phases the worker runs now
  build only what it serves and the filter below removes nothing — it has
  become the assertion that nothing crept back. It stays because the allowlist
  and the route table must keep being one fact read from two ends.

* **The filter fails loudly.** A route named here that construction did not
  produce raises at boot instead of yielding a worker that is quietly missing
  its embedding surface. That is the failure mode a later WP will actually hit.

The browser middleware (CORS, the CSRF origin guard) and the ``/static`` +
``/icons`` mounts stay on the application object — they are attached by
``phase_web`` — but the UI routes they serve are gone from the worker, which is
correct: the worker is a loopback process the host starts for itself, and every
seam on it is still behind ``require_user`` plus the seam switch.
"""

from __future__ import annotations

from typing import Any, List, Set, Tuple

#: ``(method, path)`` for each product route v11.6.0 leaves in Python —
#: docs/v11.6.0_ONE_DOOR_PLAN.md §최종 Python 워커 표면, cross-checked against
#: the KEEP_WORKER table of the route scout, then narrowed by §W3b (ingest,
#: drain/rebuild, voice capture and the four document creators went native) and
#: widened by §4a (the model pull came back). Paths are FastAPI's, converters
#: included, so this compares to ``APIRoute.path`` without normalisation.
#:
#: This tuple, through :func:`worker_route_keys`, is the **one** source of the
#: gateway's proxy allowlist. ``rust/fixtures/worker_allowlist.json`` is its
#: committed projection, regenerated by
#: ``scripts/gen_worker_allowlist_fixture.py`` and pinned by
#: ``tests/unit/test_worker_allowlist.py`` — so a route added or removed here
#: without regenerating fails CI instead of silently opening or closing a door
#: in the Rust front door.
WORKER_ROUTES: Tuple[Tuple[str, str], ...] = (
    # AI-Worker seam (v11.5.1; /agent/change-proposal retired by WP-P1 —
    # proposal state is native platform state and a stateless worker has no
    # verdict to give)
    ("POST", "/agent/llm"),
    ("POST", "/agent/tool"),
    # supervisor liveness + access posture
    ("GET", "/health"),
    # embedding production (drain/rebuild are native — W3b)
    ("GET", "/api/embeddings/status"),
    ("GET", "/api/embeddings/providers"),
    # MLX model + engine lifecycle (in-process only)
    ("GET", "/models"),
    ("POST", "/models/load"),
    ("POST", "/models/switch/{model_id:path}"),
    ("DELETE", "/models/unload/{model_id:path}"),
    ("DELETE", "/models/unload-all"),
    ("POST", "/engines/prepare-model"),
    ("POST", "/engines/prepare-model/stream"),
    # The download itself is huggingface_hub / ollama running in *this*
    # interpreter, which is the same reason the six lines above stay: model
    # management is the worker's box. The gateway proxies it rather than
    # shipping a native consent check in front of a 501 (v11.6.0 gateway
    # integration §4a).
    ("POST", "/engines/pull-model"),
    # document parser (create_* + upload are native — W3b)
    ("POST", "/tools/read_document"),
    ("GET", "/tools/pdf_pages"),
    ("GET", "/api/ingestion/multimodal"),
    # local ASR status (POST /api/capture/voice is native — W3b)
    ("GET", "/api/capture/voice/status"),
)

#: Retired by W3b — ingest is native. Kept as an empty tuple so imports
#: (`GRAPH_WRITER_ROUTES`) and `worker_route_keys()` stay stable.
GRAPH_WRITER_ROUTES: Tuple[Tuple[str, str], ...] = ()

#: The seams v11.6.0 adds (WP-I6 + WP-R4's streaming completion). Mounted here
#: and nowhere else. ``/worker/chat/record-turn`` was the third: WP-W3a moved
#: the redact → audit → store → ingest chain into ``lattice-chat`` and proved
#: the seam is requested zero times, and WP-P1 deleted the handler with the
#: conversation store it wrote through.
WORKER_SEAM_ROUTES: Tuple[Tuple[str, str], ...] = (
    ("GET", "/worker/sysinfo"),
    ("POST", "/worker/llm/stream"),
)

#: The pure-compute seams of Wave 2.5 §W2 (``latticeai/api/worker_compute.py``).
#: Kept apart from :data:`WORKER_SEAM_ROUTES` because they age in the opposite
#: direction: the state seams above are retired once §W3 lands the native write
#: engine, while these nine are what the worker is *for* once Rust owns every
#: write. Mounted here and nowhere else.
WORKER_COMPUTE_ROUTES: Tuple[Tuple[str, str], ...] = (
    ("POST", "/worker/embed"),
    ("POST", "/worker/parse"),
    ("POST", "/worker/render/docx"),
    ("POST", "/worker/render/xlsx"),
    ("POST", "/worker/render/pptx"),
    ("POST", "/worker/render/pdf"),
    ("POST", "/worker/asr"),
    ("POST", "/worker/multimodal/describe"),
    ("POST", "/worker/extract"),
)


def worker_route_keys() -> Set[Tuple[str, str]]:
    """Every ``(method, path)`` a worker process may answer."""
    return (
        set(WORKER_ROUTES)
        | set(GRAPH_WRITER_ROUTES)
        | set(WORKER_SEAM_ROUTES)
        | set(WORKER_COMPUTE_ROUTES)
    )



def _route_keys(route: Any) -> Set[Tuple[str, str]]:
    """``{(method, path)}`` for one API route — every method it answers.

    A route is kept only when *all* of its methods are on the allowlist, so a
    path that also serves an un-allowlisted verb cannot slip through on the
    strength of the one verb the worker wanted.
    """
    return {(str(method), str(route.path)) for method in route.methods}


def phase_worker_routes(ctx: Any) -> None:
    """Mount the v11.6.0 seams, then reduce the app to the worker surface.

    Runs *after* the ordinary build phases: it needs the model router and the
    resolved embedder. It publishes nothing onto the context — the profile is a
    decision about the application object, not more assembly state.
    """
    from latticeai.api.worker_compute import create_worker_compute_router
    from latticeai.api.worker_seams import create_worker_seams_router

    app = ctx.app
    app.include_router(
        create_worker_seams_router(
            require_user=ctx.require_user,
            enforce_rate_limit=ctx.enforce_rate_limit,
            model_router=getattr(ctx, "model_router", None),
        )
    )
    # The compute seams take the *resolved* embedder and the same injected
    # multimodal ports the ingestion path holds, so a vector or a caption
    # produced through HTTP is the one this process would have produced
    # in-process. ``getattr`` because a worker built without a Brain still boots
    # — each seam reports the absence rather than failing construction.
    ports = getattr(ctx, "MULTIMODAL_PORTS", None)
    app.include_router(
        create_worker_compute_router(
            embedder=getattr(ctx, "EMBEDDER", None),
            transcriber=getattr(ports, "transcriber", None),
            multimodal_ports=ports,
            require_user=ctx.require_user,
            enforce_rate_limit=ctx.enforce_rate_limit,
        )
    )
    apply_worker_route_filter(app)


def _included_router(route: Any) -> Any:
    """The router behind an ``include_router`` entry, or ``None``.

    FastAPI ≥ 0.140 stopped flattening ``include_router`` into the application's
    own route list and appends a ``_IncludedRouter`` wrapper instead. A filter
    that only understood the flat shape saw *zero* API routes on the newer
    release and raised "the build produced no route for …" for the entire
    surface — a boot failure that depends on which FastAPI a fresh resolve
    picked, which is the worst kind. Read through the wrapper by duck-typing
    (``original_router``) rather than importing a private class, so neither
    release is the one this file is written against.
    """
    inner = getattr(route, "original_router", None)
    return inner if inner is not None and hasattr(inner, "routes") else None


def apply_worker_route_filter(app: Any) -> None:
    """Keep the worker's routes and FastAPI's own doc routes; drop the rest.

    ``/openapi.json`` survives because the worker-only schema is one half of
    the v11.6.0 OpenAPI composer (plan §설계 결정 4); the ``/static`` and
    ``/icons`` mounts do not, because a worker serves no UI.

    Since WP-P1 this removes nothing — construction produces exactly the worker
    surface — so what it really is now is the assertion that nothing crept back
    in, and that every route the allowlist promises was actually built.
    """
    from fastapi.routing import APIRoute
    from starlette.routing import Mount

    wanted = worker_route_keys()
    present: Set[Tuple[str, str]] = set()

    def _prune(routes: List[Any]) -> List[Any]:
        kept: List[Any] = []
        for route in list(routes):
            included = _included_router(route)
            if included is not None:
                included.routes = _prune(included.routes)
                if included.routes:
                    kept.append(route)
                continue
            if isinstance(route, APIRoute):
                keys = _route_keys(route)
                if keys <= wanted:
                    present.update(keys)
                    kept.append(route)
                continue
            if isinstance(route, Mount):
                # ``/static`` and ``/icons``: a worker serves no UI.
                continue
            # FastAPI's own ``/openapi.json``, ``/docs``, ``/redoc``.
            kept.append(route)
        return kept

    kept = _prune(app.router.routes)
    missing = sorted(wanted - present)
    if missing:
        raise RuntimeError(
            "worker profile: the build produced no route for "
            + ", ".join(f"{method} {path}" for method, path in missing)
        )
    app.router.routes = kept
    # The schema was never generated at this point, but a caller that asked for
    # it before pruning would otherwise be served the product route table.
    app.openapi_schema = None


__all__ = [
    "GRAPH_WRITER_ROUTES",
    "WORKER_COMPUTE_ROUTES",
    "WORKER_ROUTES",
    "WORKER_SEAM_ROUTES",
    "apply_worker_route_filter",
    "phase_worker_routes",
    "worker_route_keys",
]
