//! `create_web_project` — the one tool that writes a whole tree.
//!
//! The seven files are byte copies of `latticeai.tools.filesystem`'s literals,
//! and the order they are written in is the order Python's dict yields, because
//! `created_files` records it and the critic reads that list. `package.json` is
//! built from a struct rather than a string so the one interpolated value (the
//! project name) cannot break the JSON, and serialised with `to_string_pretty`,
//! which is `json.dumps(..., ensure_ascii=False, indent=2)` byte for byte.

use serde::Serialize;
use serde_json::{json, Map, Value};

use crate::parse::pystr::is_truthy;
use crate::tools::files::{file_size, io_error};
use crate::tools::sandbox::{resolve_soft, ToolError, Workspace};

/// `package.json`, in Python's key order.
#[derive(Debug, Serialize)]
struct PackageJson {
    name: String,
    private: bool,
    version: &'static str,
    #[serde(rename = "type")]
    module_type: &'static str,
    scripts: Scripts,
    dependencies: Dependencies,
    #[serde(rename = "devDependencies")]
    dev_dependencies: DevDependencies,
}

#[derive(Debug, Serialize)]
struct Scripts {
    dev: &'static str,
    build: &'static str,
    preview: &'static str,
}

#[derive(Debug, Serialize)]
struct Dependencies {
    react: &'static str,
    #[serde(rename = "react-dom")]
    react_dom: &'static str,
}

#[derive(Debug, Serialize)]
struct DevDependencies {
    #[serde(rename = "@vitejs/plugin-react")]
    plugin_react: &'static str,
    vite: &'static str,
}

const INDEX_HTML: &str = r##"<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite React App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
"##;

const VITE_CONFIG: &str = r##"import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
"##;

const README: &str = r##"# Vite React App

## Run

```bash
npm install
npm run dev
```

## Build

```bash
npm run build
npm run preview
```

## Lattice AI Notes

- Inspect `package.json` and existing config files before adding new libraries.
- If you add Tailwind CSS, framer-motion, TypeScript, or other tooling, add the required config files too.
- Do not report the app as complete until `npm run build` succeeds.
"##;

const MAIN_JSX: &str = r##"import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
"##;

const APP_JSX: &str = r##"import { useState } from 'react'

export default function App() {
  const [count, setCount] = useState(0)
  return (
    <main style={{ maxWidth: 760, margin: '48px auto', padding: '0 20px', fontFamily: 'system-ui, sans-serif' }}>
      <h1>Vite + React</h1>
      <p>Starter generated by Lattice AI agent.</p>
      <p style={{ color: '#555', lineHeight: 1.6 }}>
        Inspect the current setup before adding new UI libraries, then verify
        changes with <code>npm run build</code>.
      </p>
      <button onClick={() => setCount((c) => c + 1)}>count is {count}</button>
    </main>
  )
}
"##;

const INDEX_CSS: &str = r##"* { box-sizing: border-box; }
body { margin: 0; background: #f6f7fb; color: #111; }
button { padding: 10px 14px; border-radius: 10px; border: 1px solid #d6d6d6; background: #fff; cursor: pointer; }
"##;

/// `Path(path).name.replace(" ", "-").lower() or "vite-react-app"`.
fn package_name(path: &str) -> String {
    let name = crate::kernel::transcript::path_name(path)
        .replace(' ', "-")
        .to_lowercase();
    if name.is_empty() {
        "vite-react-app".to_string()
    } else {
        name
    }
}

/// `str((a.get(key, default)) or "").strip().lower()` — two layers of default:
/// the handler's (an **absent** key is `react`/`vite`) and the tool's (a
/// *present* falsy value becomes `""`, which matches nothing and is refused).
fn selector(args: &Map<String, Value>, key: &str, handler_default: &str) -> String {
    crate::tools::args::defaulted_str(args, key, handler_default)
        .trim()
        .to_lowercase()
}

/// `create_web_project(path, framework="react", template="vite")`.
pub fn create_web_project(
    workspace: &Workspace,
    args: &Map<String, Value>,
) -> Result<Value, ToolError> {
    let framework = selector(args, "framework", "react");
    let template = selector(args, "template", "vite");
    if framework != "react" || template != "vite" {
        return Err(ToolError::tool(
            "Only React + Vite template is currently supported.",
        ));
    }
    // `if not path` — Python tests the raw value, so any falsy one (absent,
    // empty, null) is the same refusal, and a truthy non-string is the stated
    // type deviation rather than a `PurePath / int` crash.
    let path = match args.get("path").filter(|value| is_truthy(value)) {
        None => String::new(),
        Some(Value::String(text)) => text.clone(),
        Some(_) => return Err(ToolError::tool("'path' must be a string.")),
    };
    if path.is_empty() {
        return Err(ToolError::tool("Project path is required."));
    }

    let root = workspace.resolve(&path)?;
    std::fs::create_dir_all(&root).map_err(io_error)?;

    let package = serde_json::to_string_pretty(&PackageJson {
        name: package_name(&path),
        private: true,
        version: "0.0.0",
        module_type: "module",
        scripts: Scripts {
            dev: "vite",
            build: "vite build",
            preview: "vite preview",
        },
        dependencies: Dependencies {
            react: "^18.3.1",
            react_dom: "^18.3.1",
        },
        dev_dependencies: DevDependencies {
            plugin_react: "^4.3.1",
            vite: "^5.4.0",
        },
    })
    .map_err(|error| ToolError::tool(error.to_string()))?
        + "\n";

    let files: [(&str, &str); 7] = [
        ("package.json", &package),
        ("index.html", INDEX_HTML),
        ("vite.config.js", VITE_CONFIG),
        ("README.md", README),
        ("src/main.jsx", MAIN_JSX),
        ("src/App.jsx", APP_JSX),
        ("src/index.css", INDEX_CSS),
    ];

    let mut created: Vec<String> = Vec::with_capacity(files.len());
    let mut total: u64 = 0;
    for (relative, content) in files {
        let target = resolve_soft(&root.join(relative));
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent).map_err(io_error)?;
        }
        std::fs::write(&target, content).map_err(io_error)?;
        created.push(workspace.relative(&target));
        total += file_size(&target);
    }

    Ok(json!({
        "path": workspace.relative(&root),
        "framework": framework,
        "template": template,
        "created_files": created,
        "file_count": created.len(),
        "bytes": total,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn workspace() -> (tempfile::TempDir, Workspace) {
        let dir = tempfile::tempdir().expect("tempdir");
        let workspace = Workspace::new(dir.path().join("agent_workspace")).expect("workspace");
        (dir, workspace)
    }

    fn args(value: Value) -> Map<String, Value> {
        value.as_object().expect("object").clone()
    }

    #[test]
    fn the_scaffold_is_seven_files_in_pythons_order() {
        let (_dir, workspace) = workspace();
        let result = create_web_project(&workspace, &args(json!({"path": "My Todo App"})))
            .expect("scaffold");
        assert_eq!(result["file_count"], 7);
        assert_eq!(result["framework"], "react");
        assert_eq!(result["template"], "vite");
        assert_eq!(
            result["created_files"],
            json!([
                "My Todo App/package.json",
                "My Todo App/index.html",
                "My Todo App/vite.config.js",
                "My Todo App/README.md",
                "My Todo App/src/main.jsx",
                "My Todo App/src/App.jsx",
                "My Todo App/src/index.css",
            ])
        );
        let bytes = result["bytes"].as_u64().expect("bytes");
        assert!(bytes > 2_000, "{bytes}");
    }

    #[test]
    fn the_package_json_is_pythons_json_dumps() {
        let (_dir, workspace) = workspace();
        create_web_project(&workspace, &args(json!({"path": "My Todo App"}))).expect("scaffold");
        let body = std::fs::read_to_string(workspace.root().join("My Todo App/package.json"))
            .expect("package.json");
        assert_eq!(
            body,
            "{\n  \"name\": \"my-todo-app\",\n  \"private\": true,\n  \"version\": \"0.0.0\",\n  \
\"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"vite\",\n    \"build\": \"vite build\",\n    \
\"preview\": \"vite preview\"\n  },\n  \"dependencies\": {\n    \"react\": \"^18.3.1\",\n    \
\"react-dom\": \"^18.3.1\"\n  },\n  \"devDependencies\": {\n    \"@vitejs/plugin-react\": \"^4.3.1\",\n    \
\"vite\": \"^5.4.0\"\n  }\n}\n"
        );
    }

    #[test]
    fn only_react_plus_vite_is_supported_and_the_path_is_required() {
        let (_dir, workspace) = workspace();
        for bad in [
            json!({"path": "app", "framework": "vue"}),
            json!({"path": "app", "template": "webpack"}),
            json!({"path": "app", "framework": null}),
        ] {
            assert_eq!(
                create_web_project(&workspace, &args(bad))
                    .expect_err("unsupported")
                    .message,
                "Only React + Vite template is currently supported."
            );
        }
        for empty in [json!({}), json!({"path": ""}), json!({"path": null})] {
            assert_eq!(
                create_web_project(&workspace, &args(empty))
                    .expect_err("no path")
                    .message,
                "Project path is required."
            );
        }
        assert_eq!(
            create_web_project(&workspace, &args(json!({"path": "../out"})))
                .expect_err("escape")
                .message,
            "Path escapes the agent workspace."
        );
    }

    #[test]
    fn the_defaults_are_react_and_vite() {
        // The handler passes `a.get("framework", "react")`, so an absent key is
        // supported and a *present* wrong one is not.
        let (_dir, workspace) = workspace();
        assert!(create_web_project(&workspace, &args(json!({"path": "a"}))).is_ok());
        assert_eq!(package_name("a/b c"), "b-c");
        assert_eq!(package_name(""), "vite-react-app");
    }
}
