"""v3.3.1 version-consistency guard.

Lattice AI keeps a single release version. The runtime canonical is
``latticeai.core.workspace_os.WORKSPACE_OS_VERSION``; everything user-facing
must agree with it:

* ``latticeai.__version__`` (Python package)
* ``pyproject.toml`` / ``package.json`` / editor and browser extensions
* the React browser asset manifest (``static/app/asset-manifest.json``)
* the release-tracking subsystem constants that historically moved with the
  release (marketplace, multi-agent)

This test fails the moment any of those drift, which is what made the v3.1.0
string linger in the Settings UI before this release.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def _read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


def _json(rel: str) -> dict:
    return json.loads(_read(rel))


def _canonical() -> str:
    from latticeai.core.workspace_os import WORKSPACE_OS_VERSION

    return WORKSPACE_OS_VERSION


def test_python_constants_agree():
    from lattice_brain import __version__ as brain_version
    from lattice_brain.runtime.multi_agent import MULTI_AGENT_VERSION
    from latticeai import __version__
    from latticeai.core.marketplace import MARKETPLACE_VERSION

    v = _canonical()
    assert __version__ == v
    assert brain_version == v
    assert v == MARKETPLACE_VERSION
    assert v == MULTI_AGENT_VERSION


def test_pyproject_version_agrees():
    m = re.search(r'(?m)^version\s*=\s*"([^"]+)"', _read("pyproject.toml"))
    assert m, "version not found in pyproject.toml"
    assert m.group(1) == _canonical()


def test_package_json_versions_agree():
    v = _canonical()
    assert _json("package.json")["version"] == v
    assert _json("vscode-extension/package.json")["version"] == v
    assert _json("browser-extension/manifest.json")["version"] == v
    assert _json("src-tauri/tauri.conf.json")["version"] == v


def test_tauri_cargo_version_agrees():
    m = re.search(r'(?m)^version\s*=\s*"([^"]+)"', _read("src-tauri/Cargo.toml"))
    assert m, "version not found in src-tauri/Cargo.toml"
    assert m.group(1) == _canonical()


RUST_CRATES = ("lattice-core", "lattice-host", "lattice-retrieval")


def test_rust_workspace_version_agrees():
    # 11.4.0 added the rust/ cargo workspace. The three crates declare
    # `version.workspace = true`, so the workspace root is the only hand-edited
    # copy — this asserts that too, because the moment a crate spells its own
    # version out there are two sources of truth again.
    v = _canonical()
    m = re.search(r'(?m)^version\s*=\s*"([^"]+)"', _read("rust/Cargo.toml"))
    assert m, "version not found in rust/Cargo.toml [workspace.package]"
    assert m.group(1) == v
    for crate in RUST_CRATES:
        manifest = _read(f"rust/{crate}/Cargo.toml")
        assert "version.workspace = true" in manifest, (
            f"{crate} must inherit the workspace version, not declare its own"
        )


def test_rust_lockfiles_agree():
    # Both lockfiles resolve the workspace crates by version: rust/Cargo.lock
    # for the workspace itself, src-tauri/Cargo.lock because the desktop shell
    # depends on lattice-host by path. A stale lock is a file the next cargo
    # build rewrites underneath a tagged release.
    v = _canonical()
    for lock in ("rust/Cargo.lock", "src-tauri/Cargo.lock"):
        text = _read(lock)
        for crate in RUST_CRATES:
            found = re.search(rf'name = "{crate}"\nversion = "([^"]+)"', text)
            assert found, f"{crate} not found in {lock}"
            assert found.group(1) == v, f"{crate} in {lock} is {found.group(1)}, expected {v}"


def test_npm_lockfiles_agree():
    v = _canonical()
    root_lock = _json("package-lock.json")
    assert root_lock["version"] == v
    assert root_lock["packages"][""]["version"] == v
    ext_lock = _json("vscode-extension/package-lock.json")
    assert ext_lock["version"] == v
    assert ext_lock["packages"][""]["version"] == v


def test_asset_manifest_version_agrees():
    # Regenerated by scripts/build_frontend_assets.mjs, which sources the version
    # from package.json. Guard the committed artifact too.
    assert _json("static/app/asset-manifest.json")["version"] == _canonical()


def test_no_stale_hardcoded_version_in_settings_view():
    # The Settings About panel must NOT hard-code a version literal; it reads
    # /health at runtime. Any vX.Y.Z literal here is a regression.
    app = _read("frontend/src/App.tsx")
    assert not re.search(r'v\d+\.\d+\.\d+(?! Release Candidate)', app), (
        "frontend shell must not hard-code a release version except the RC label; read runtime versions from /health"
    )
