"""v3.3.1 version-consistency guard.

Lattice AI keeps a single release version. The runtime canonical is
``latticeai.__version__``; everything user-facing must agree with it.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def _read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


def _json(rel: str) -> dict:
    return json.loads(_read(rel))


def _canonical() -> str:
    from latticeai import __version__

    return __version__


def test_python_constants_agree():
    from lattice_brain import __version__ as brain_version
    from latticeai import __version__

    v = _canonical()
    assert __version__ == v
    assert brain_version == v


def test_pyproject_version_agrees():
    m = re.search(r'(?m)^version\s*=\s*"([^"]+)"', _read("pyproject.toml"))
    assert m, "version not found in pyproject.toml"
    assert m.group(1) == _canonical()


def test_package_json_versions_agree():
    v = _canonical()
    assert _json("package.json")["version"] == v
    assert _json("vscode-extension/package.json")["version"] == v
    assert _json("browser-extension/manifest.json")["version"] == v
    assert _json("src-tauri/tauri.conf.json")["version"] == v


def test_tauri_cargo_version_agrees():
    m = re.search(r'(?m)^version\s*=\s*"([^"]+)"', _read("src-tauri/Cargo.toml"))
    assert m, "version not found in src-tauri/Cargo.toml"
    assert m.group(1) == _canonical()


# Every member of the rust/ workspace. Through 11.5.1 this tuple named only the
# three Phase-1 crates, which is why the Phase-2/3/4 crates could sit at a stale
# version in both lockfiles without a single test noticing.
RUST_CRATES = (
    "lattice-agent",
    "lattice-auth",
    "lattice-chat",
    "lattice-core",
    "lattice-host",
    "lattice-ingest",
    "lattice-jobs",
    "lattice-platform",
    "lattice-retrieval",
)


def test_rust_crate_list_covers_every_workspace_member():
    # The list above is hand-written; this is what keeps it honest. A new crate
    # added to `members` without being added here would otherwise silently opt
    # out of the version sync, exactly as the Phase-2/3/4 crates did.
    members = re.search(r"(?ms)^members = \[(.*?)\]", _read("rust/Cargo.toml"))
    assert members, "members not found in rust/Cargo.toml [workspace]"
    declared = tuple(sorted(re.findall(r'"([^"]+)"', members.group(1))))
    assert declared == tuple(sorted(RUST_CRATES))


def test_rust_workspace_version_agrees():
    # 11.4.0 added the rust/ cargo workspace. Every crate declares
    # `version.workspace = true`, so the workspace root is the only hand-edited
    # copy — this asserts that too, because the moment a crate spells its own
    # version out there are two sources of truth again.
    v = _canonical()
    m = re.search(r'(?m)^version\s*=\s*"([^"]+)"', _read("rust/Cargo.toml"))
    assert m, "version not found in rust/Cargo.toml [workspace.package]"
    assert m.group(1) == v
    for crate in RUST_CRATES:
        manifest = _read(f"rust/{crate}/Cargo.toml")
        assert "version.workspace = true" in manifest, (
            f"{crate} must inherit the workspace version, not declare its own"
        )


def test_rust_lockfiles_agree():
    # Both lockfiles resolve the workspace crates by version: rust/Cargo.lock
    # for the workspace itself, src-tauri/Cargo.lock because the desktop shell
    # depends on lattice-host by path. A stale lock is a file the next cargo
    # build rewrites underneath a tagged release.
    v = _canonical()
    for lock in ("rust/Cargo.lock", "src-tauri/Cargo.lock"):
        text = _read(lock)
        for crate in RUST_CRATES:
            found = re.search(rf'name = "{crate}"\nversion = "([^"]+)"', text)
            assert found, f"{crate} not found in {lock}"
            assert found.group(1) == v, f"{crate} in {lock} is {found.group(1)}, expected {v}"


def test_npm_lockfiles_agree():
    v = _canonical()
    root_lock = _json("package-lock.json")
    assert root_lock["version"] == v
    assert root_lock["packages"][""]["version"] == v
    ext_lock = _json("vscode-extension/package-lock.json")
    assert ext_lock["version"] == v
    assert ext_lock["packages"][""]["version"] == v


def test_asset_manifest_version_agrees():
    # Regenerated by scripts/build_frontend_assets.mjs, which sources the version
    # from package.json. Guard the committed artifact too.
    assert _json("static/app/asset-manifest.json")["version"] == _canonical()


def test_no_stale_hardcoded_version_in_settings_view():
    # The Settings About panel must NOT hard-code a version literal; it reads
    # /health at runtime. Any vX.Y.Z literal here is a regression.
    app = _read("frontend/src/App.tsx")
    assert not re.search(r'v\d+\.\d+\.\d+(?! Release Candidate)', app), (
        "frontend shell must not hard-code a release version except the RC label; read runtime versions from /health"
    )
