"""v3.3.1 version-consistency guard.

Lattice AI keeps a single release version. The runtime canonical is
``latticeai.core.workspace_os.WORKSPACE_OS_VERSION``; everything user-facing
must agree with it:

* ``latticeai.__version__`` (Python package)
* ``pyproject.toml`` / ``package.json`` / editor and browser extensions
* the React browser asset manifest (``static/app/asset-manifest.json``)
* the release-tracking subsystem constants that historically moved with the
  release (marketplace, multi-agent)

This test fails the moment any of those drift, which is what made the v3.1.0
string linger in the Settings UI before this release.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def _read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


def _json(rel: str) -> dict:
    return json.loads(_read(rel))


def _canonical() -> str:
    from latticeai.core.workspace_os import WORKSPACE_OS_VERSION

    return WORKSPACE_OS_VERSION


def test_python_constants_agree():
    from latticeai import __version__
    from lattice_brain import __version__ as brain_version
    from latticeai.core.marketplace import MARKETPLACE_VERSION
    from lattice_brain.runtime.multi_agent import MULTI_AGENT_VERSION

    v = _canonical()
    assert __version__ == v
    assert brain_version == v
    assert MARKETPLACE_VERSION == v
    assert MULTI_AGENT_VERSION == v


def test_pyproject_version_agrees():
    m = re.search(r'(?m)^version\s*=\s*"([^"]+)"', _read("pyproject.toml"))
    assert m, "version not found in pyproject.toml"
    assert m.group(1) == _canonical()


def test_package_json_versions_agree():
    v = _canonical()
    assert _json("package.json")["version"] == v
    assert _json("vscode-extension/package.json")["version"] == v
    assert _json("browser-extension/manifest.json")["version"] == v
    assert _json("src-tauri/tauri.conf.json")["version"] == v


def test_tauri_cargo_version_agrees():
    m = re.search(r'(?m)^version\s*=\s*"([^"]+)"', _read("src-tauri/Cargo.toml"))
    assert m, "version not found in src-tauri/Cargo.toml"
    assert m.group(1) == _canonical()


def test_npm_lockfiles_agree():
    v = _canonical()
    root_lock = _json("package-lock.json")
    assert root_lock["version"] == v
    assert root_lock["packages"][""]["version"] == v
    ext_lock = _json("vscode-extension/package-lock.json")
    assert ext_lock["version"] == v
    assert ext_lock["packages"][""]["version"] == v


def test_asset_manifest_version_agrees():
    # Regenerated by scripts/build_frontend_assets.mjs, which sources the version
    # from package.json. Guard the committed artifact too.
    assert _json("static/app/asset-manifest.json")["version"] == _canonical()


def test_no_stale_hardcoded_version_in_settings_view():
    # The Settings About panel must NOT hard-code a version literal; it reads
    # /health at runtime. Any vX.Y.Z literal here is a regression.
    app = _read("frontend/src/App.tsx")
    assert not re.search(r'v\d+\.\d+\.\d+(?! Release Candidate)', app), (
        "frontend shell must not hard-code a release version except the RC label; read runtime versions from /health"
    )
